---
# tasks file for rsysloging-server

- name: Install rsyslog-relp
  apt:
    name: rsyslog-relp

- name: "rsysloging server conf"
  template:
    src: rsysloging_server.j2
    dest: /etc/rsyslog.d/server.conf
  become: yes

- name: "Copy client-cert for rsyslog"
  template:
    src: client-cert.pem
    dest: /etc/rsyslog.d/client-cert.pem
  become: yes

- name: "Copy client-key for rsyslog"
  template:
    src: client-key.pem
    dest: /etc/rsyslog.d/client-key.pem
  become: yes

- name: "Restart rsyslog service"
  service:
    name: rsyslog
    state: restarted
    enabled: yes

- name: Open port on man
  command: iptables -A INPUT -p tcp --dport 514 --jump ACCEPT
  become: yes

- name: Save iptables
  command: iptables-save
  become: yes