---
# tasks file for rsysloging-server
 
- name: check existence of required variables
  fail:
      msg: required variable '{{ item.key }}' is undefined
  when: item.value is undefined or not item.value
  with_dict: '{{ clc_required_vars }}'

- name: Install gnutls plugin for rsyslog
  apt:
    name: rsyslog-gnutls
    
- name: "Instalation rsyslog relp  (state=present is optional)"
  apt:
    name: rsyslog-relp

- name: "command-monitoring-collector.conf"
  template:
    src: command-monitoring-collector.conf.j2
    dest: /etc/rsyslog.d/command-monitoring-collector.conf
  notify: clc_rsyslog_restart

- name: Open port on man
  command: iptables -A INPUT -p tcp --dport 514 --jump ACCEPT

- name: Save iptables
  command: iptables-save
